### ISSUE TITLE
Почему Scipio был удален из PyPI?

### ISSUE THREAD

**Issue by adw0rd** [isagalaev/scipio#4]
Привет, я хотел переустановить venv с блогом на marcus, но зависимость scipio куда-то исчезла с PyPI. Это временно или ты решил избавится от проекта?

**Comment by isagalaev** [comment]
Привет! Я даже не уверен, что оно там когда-то было. По крайней мере, я не помню, чтобы я его туда загружал. Но в любом случае, его совершенно точно не имеет смысла развивать уже. Эта функциональность лучше покрывается django-social и аналогами: https://www.djangopackages.com/search/?q=social+auth
